### ISSUE TITLE
question

### ISSUE THREAD

**Issue by soniapello** [gregja/zdogXperiments#1]
Hi Gregory 
Not an issue but a question about an extension.
Would you consider adding an .obj import for importing 3d object ?

**Comment by gregja** [comment]
Hi, sorry for my late answer,
I don't know if I answer correctly to your demand, but I implemented an OBJ import on the project. You can see it in live on that page : 
http://ledefrichoir.com/labo/zdogXperiments/sources/zdog_obj_v3.html
Best regards
Gregory
